language: cpp
compiler: clang
branches:
  only:
  - master
before_install:
- sudo apt-get install -y libwxbase3.0-dev libwxgtk3.0-dev
script:
- cmake .
- cmake --build .
before_deploy:
- ls --color=auto -alF .
deploy:
  provider: releases
  api_key:
    secure: C7i5V0OpFJwQLy3gyl7UKpoTRIw19KLBxfCQXH0fRTSpO0VLq1NuL0N1yGqBByr3CQQQIJFXnC6JtD9IGfnv0Vcs8zRxc3Hc3ZSS22OtQoy7bIOB7G+1PrkNpl/D2Bk1tVBWRsUczZNfNO3xU5RXxFuNT6UbJGjmBPaIOfgJzkNdtQ0hGFCsMSLkiDdj3QYuLxhwipFjMLNmX1QvhQvflWDW9VwenMBlNWuMuCqQfikKzrDE90dh4rR36pb5Y6YAlHUe4hRVHoJ9YRKXpB/zaI/uSkYYSjH5dCXrY17AZ1nnMHmjwOUKeNkAwcWZnFhnQCPNBnHlEGL2eeXAJVbLRFz4kIskW5YqyKmtta5OA/pDScy/TRXlOrxZigsWVfeu8igFMDLmB6yIp8g9ViARamR/xPbdage4R/m6kTVCtENgyV9rv526qWUG5aUDjyBMXGb1D3MWRIXQWAYYZl0tfPKJlsa2cWN3LlcAj4UBGJ6hVv1vFbDBZQbyivDIoEK2I4jxhyv8Eg3Xa32Hk1lBWfFF/sZMImUuR63kcs41bideCm6hJBk7E0CvX+xkkmgrcywrREKDhFsNL8POEqqg8wz53oUtnO0xRC+/4wT6tGMYgkdxjg8VbRLvNWFyANfNj741EprNvtr3sdCCRRp5slL648nSqWpsHfljc39gak4=
  file: HLMWADExplorer
  skip_cleanup: true
  on:
    repo: nnn1590/HLMWadExplorer
